import { execSync } from "child_process";
import { Octokit } from "@octokit/rest";

const octokit = new Octokit({ auth: process.env.GH_TOKEN });

const repo = process.env.REPO.split("/");
const owner = repo[0];
const repoName = repo[1];

const issueBody = process.env.ISSUE_BODY;
const issueNumber = process.env.ISSUE_NUMBER;

(async () => {
  const branch = `clean/${Date.now()}`;

  execSync(`git checkout -b ${branch}`);

  execSync(`echo "Automated cleanup from issue #${issueNumber}" >> CLEANLOG.txt`);
  execSync(`git add .`);
  execSync(`git -c user.name="HouseLearningCleaned[bot]" -c user.email="bot@houselearning.com" commit -m "Automated cleanup draft PR"`);

  execSync(`git push origin ${branch}`);

  await octokit.pulls.create({
    owner,
    repo: repoName,
    title: `Automated Cleanup (Issue #${issueNumber})`,
    head: branch,
    base: "main",
    draft: true,
    body: "This PR was automatically generated by HouseLearningCleaned[bot]."
  });
})();
